embedding_size: 64              # (int) The embedding size of users and items.
n_layers: 2                     # (int) The number of layers in LightGCN.
reg_weight: 1e-04               # (float) The L2 regularization weight.


# 模型参数配置

hidden_size: 64
n_heads: 2
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
step: 1
loss_type: 'CE'
initializer_range: 0.02

# 训练参数
learning_rate: 0.001
epochs: 100
train_batch_size: 256
